
title: Membumikan Git
email: ajiwoke@gmail.com
description: >- 
  Wesite ini bertujuan untuk menjelaskan tentang git dengan orang awam menggunakan bahasa indonesia.
baseurl: "" 
url: "localhost:4000" 
twitter_username: prayogo_tirto
github_username:  ajitirto

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
