/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "primary": "#ffffff",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "primary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary": "#003824",
        "on-secondary-container": "#e6ecff",
        "secondary": "#adc6ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-dim": "#131313",
        "on-surface-variant": "#c4c7c8",
        "on-tertiary-fixed": "#002113",
        "surface": "#131313",
        "on-tertiary-container": "#00734e",
        "tertiary": "#ffffff",
        "surface-tint": "#c6c6c7",
        "on-primary-fixed": "#1a1c1c",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#0566d9",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "outline": "#8e9192",
        "outline-variant": "#444748",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "primary-container": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "error": "#ffb4ab",
        "on-secondary": "#002e6a",
        "background": "#131313",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#4edea3",
        "inverse-primary": "#5d5f5f",
        "on-primary-fixed-variant": "#454747",
        "on-primary-container": "#636565",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-container": "#6ffbbe",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004395",
        "primary-fixed": "#e2e2e2",
        "on-primary": "#2f3131",
        "on-secondary-fixed": "#001a42",
        "surface-container": "#201f1f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "4rem",
        "md": "1.5rem",
        "xs": "0.5rem",
        "sm": "1rem",
        "unit": "4px",
        "lg": "2.5rem",
        "gutter": "24px",
        "container-max": "1120px"
      },
      fontFamily: {
        "display": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
